version: '3.4'

services:
  db:
    env_file: environment.env
    image: postgres:11.14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
